name: personal
description: Корпоративное приложение АО Уралэлектромедь
version: 1.0.2+9 # версия меняется только здесь, дальше она расставляестя автоматически

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # my
  http: any
  local_auth: any
  bloc: any
  flutter_bloc: any
  url_launcher: any
  contacts_service: any
  permission_handler: any
  flutter_secure_storage: any
  pull_to_refresh: any
  shared_preferences: any
  webview_flutter: any
  carousel_slider: ^1.3.1
  photo_view: any
  image_picker: any
  flutter_swiper: any
  package_info: any
  json_serializable: ^2.0.2
  firebase_core: any
  firebase_messaging: ^5.1.4
  firebase_crashlytics: ^0.1.0+3
  firebase_analytics: ^5.0.1
  extended_image: 0.6.1
  extended_image_library: 0.1.5
  tutorial_coach_mark: ^0.2.0
  file_picker: ^1.4.2
  flutter_uploader: ^1.0.5+1
  flutter_html: ^0.11.0
  flutter_svg: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/idea.png
    - assets/images/drawer_bg.jpg
    - assets/any_person.png
    - assets/updater_locker_logo.png
    - assets/food/Питание.png
    - assets/food/Кефир.png
    - assets/food/Молоко.png
    - assets/food/Молоко и пектин.png
    - assets/food/Кефир и пектин.png
    - assets/images/vacation.jpg
    - assets/TermsOfUse.html
    - assets/images/disp/mf.svg
    - assets/images/disp/arrow.svg
    - assets/images/disp/1.svg
    - assets/images/disp/2.svg
    - assets/images/disp/3.svg
    - assets/images/disp/4.svg
    - assets/images/disp/5.svg
    - assets/images/disp/6.svg
    - assets/images/disp/7.svg
    - assets/images/disp/8.svg
    - assets/images/disp/9.svg
    - assets/images/disp/f.svg
    - assets/images/disp/m.svg
    - assets/images/disp/w1.svg
    - assets/images/disp/w2.svg
    - assets/images/disp/w3.svg
    - assets/images/disp/w4.svg
    - assets/images/disp/w5.svg